CREATE USER DEALERSHIP IDENTIFIED BY A;
GRANT CONNECT, RESOURCE TO DEALERSHIP;
ALTER USER DEALERSHIP QUOTA 200M ON USERS;
CONN DEALERSHIP/A;

-- Table: Persons
CREATE TABLE Persons (
                         person_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         name VARCHAR2(50) NOT NULL,
                         identification VARCHAR2(10) NOT NULL,
                         address VARCHAR2(50) NOT NULL,
                         phone NUMBER(10) NOT NULL
);

-- Table: Vehicles
CREATE TABLE Vehicles (
                          vehicle_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          brand VARCHAR2(50) NOT NULL,
                          model VARCHAR2(50) NOT NULL,
                          engine_capacity VARCHAR2(10) NOT NULL,
                          price NUMBER(10) NOT NULL,
                          type VARCHAR2(22) NOT NULL
);

-- Table: Assignments
CREATE TABLE Assignments (
                             assignment_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                             person_id NUMBER(5) NOT NULL,
                             vehicle_id NUMBER(5) NOT NULL,
                             assignment_date DATE NOT NULL,
                             appraisal_price NUMBER(10) NOT NULL,
                             FOREIGN KEY (person_id) REFERENCES Persons(person_id),
                             FOREIGN KEY (vehicle_id) REFERENCES Vehicles(vehicle_id)
);

-- Table: Options
CREATE TABLE Options (
                         option_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         name VARCHAR2(50) NOT NULL,
                         description VARCHAR2(200) NOT NULL
);

-- Table: Vehicle_Options
CREATE TABLE Vehicle_Options (
                                 vehicle_option_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                 vehicle_id NUMBER(5) NOT NULL,
                                 option_id NUMBER(5) NOT NULL,
                                 price NUMBER(10) NOT NULL,
                                 FOREIGN KEY (vehicle_id) REFERENCES Vehicles(vehicle_id),
                                 FOREIGN KEY (option_id) REFERENCES Options(option_id)
);

-- Table: Sales
CREATE TABLE Sales (
                       sale_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                       client_id NUMBER(5) NOT NULL,
                       seller_id NUMBER(5) NOT NULL,
                       new_vehicle_id NUMBER(5) NOT NULL,
                       new_license_plate VARCHAR2(10) NOT NULL,
                       sale_date DATE NOT NULL,
                       assignment_id NUMBER(5),
                       final_price NUMBER(10) NOT NULL,
                       FOREIGN KEY (client_id) REFERENCES Persons(person_id),
                       FOREIGN KEY (seller_id) REFERENCES Persons(person_id),
                       FOREIGN KEY (new_vehicle_id) REFERENCES Vehicles(vehicle_id),
                       FOREIGN KEY (assignment_id) REFERENCES Assignments(assignment_id)
);

-- Table: Sales_Options
CREATE TABLE Sales_Options (
                               sale_option_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                               sale_id NUMBER(5) NOT NULL,
                               vehicle_option_id NUMBER(5) NOT NULL,
                               FOREIGN KEY (sale_id) REFERENCES Sales(sale_id),
                               FOREIGN KEY (vehicle_option_id) REFERENCES Vehicle_Options(vehicle_option_id)
);